version: '3.6'

services:
  alpine-apache2-reverse-proxy-forensicid-uniqueid:
    image: hackinglab/alpine-apache2-reverse-proxy-forensicid-uniqueid:latest
    environment:
      - "HL_USER_USERNAME=hacker"
      - "HL_USER_PASSWORD=compass"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/proxy-html.conf:/etc/apache2/conf-frontend.d/proxy-html.conf
